### ISSUE TITLE
Doesn't compile on arduino ide 1.8.13

### ISSUE THREAD

**Issue by zangaby** [ThingPulse/esp8266-weather-station#188]
Hello,

Fresh IDE installation, followed the steps described here:
https://docs.thingpulse.com/how-tos/Arduino-IDE-for-ESP8266/

But getting this 

```
c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o: in function `drawProgress(OLEDDisplay*, int, String)':

C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:238: undefined reference to `OpenWeatherMapCurrent::updateCurrentById(OpenWeatherMapCurrentData*, String, String)'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o:(.text._Z10updateDataP11OLEDDisplay+0x38): undefined reference to `OpenWeatherMapForecast::updateForecastsById(OpenWeatherMapForecastData*, String, String, unsigned char)'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o: in function `updateData(OLEDDisplay*)':

C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:241: undefined reference to `OpenWeatherMapCurrent::updateCurrentById(OpenWeatherMapCurrentData*, String, String)'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o: in function `updateData(OLEDDisplay*)':

sketch/OpenWeatherMapCurrent.h:93: undefined reference to `OpenWeatherMapForecast::updateForecastsById(OpenWeatherMapForecastData*, String, String, unsigned char)'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o:(.text.startup._GLOBAL__sub_I_WIFI_SSID+0xbc): undefined reference to `OpenWeatherMapCurrent::OpenWeatherMapCurrent()'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o:(.text.startup._GLOBAL__sub_I_WIFI_SSID+0xc0): undefined reference to `OpenWeatherMapForecast::OpenWeatherMapForecast()'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\WeatherStationDemo.ino.cpp.o: in function `_GLOBAL__sub_I_WIFI_SSID':

C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:97: undefined reference to `OpenWeatherMapCurrent::OpenWeatherMapCurrent()'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:98: undefined reference to `OpenWeatherMapForecast::OpenWeatherMapForecast()'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:98: undefined reference to `vtable for OpenWeatherMapForecast'

c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\user\Downloads\esp8266-weather-station-master\examples\WeatherStationDemo/WeatherStationDemo.ino:98: undefined reference to `vtable for OpenWeatherMapCurrent'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

**Comment by marcelstoer** [comment]
It's neither an issue with this code nor with the hardware.

> collect2.exe: error: ld returned 1 exit status

-> https://www.startpage.com/do/dsearch?query="collect2.exe%3A+error%3A+ld+returned+1+exit+status"
